# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\huangbiao\IVUSReviewer\main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mainwindow(object):
    def setupUi(self, Mainwindow):
        Mainwindow.setObjectName("Mainwindow")
        Mainwindow.setEnabled(True)
        Mainwindow.resize(780, 630)
        Mainwindow.setMaximumSize(QtCore.QSize(780, 637))
        self.centralwidget = QtWidgets.QWidget(Mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OpenFileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.OpenFileBtn.setGeometry(QtCore.QRect(50, 30, 112, 32))
        self.OpenFileBtn.setObjectName("OpenFileBtn")
        self.ShowFileName = QtWidgets.QLabel(self.centralwidget)
        self.ShowFileName.setGeometry(QtCore.QRect(180, 30, 521, 31))
        self.ShowFileName.setObjectName("ShowFileName")
        self.IVUSViewer = QtWidgets.QGraphicsView(self.centralwidget)
        self.IVUSViewer.setGeometry(QtCore.QRect(50, 110, 371, 371))
        self.IVUSViewer.setObjectName("IVUSViewer")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setEnabled(False)
        self.lcdNumber.setGeometry(QtCore.QRect(190, 490, 64, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setEnabled(False)
        self.horizontalSlider.setGeometry(QtCore.QRect(40, 520, 371, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.CheckBifurcation = QtWidgets.QCheckBox(self.centralwidget)
        self.CheckBifurcation.setEnabled(False)
        self.CheckBifurcation.setGeometry(QtCore.QRect(490, 190, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.CheckBifurcation.setFont(font)
        self.CheckBifurcation.setStyleSheet("QCheckBox::indicator{width :40px;height : 40px;}")
        self.CheckBifurcation.setObjectName("CheckBifurcation")
        self.CheckCalcified = QtWidgets.QCheckBox(self.centralwidget)
        self.CheckCalcified.setEnabled(False)
        self.CheckCalcified.setGeometry(QtCore.QRect(490, 360, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.CheckCalcified.setFont(font)
        self.CheckCalcified.setStyleSheet("QCheckBox::indicator{width :40px;height : 40px;}")
        self.CheckCalcified.setObjectName("CheckCalcified")
        self.CheckStent = QtWidgets.QCheckBox(self.centralwidget)
        self.CheckStent.setEnabled(False)
        self.CheckStent.setGeometry(QtCore.QRect(490, 100, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.CheckStent.setFont(font)
        self.CheckStent.setStyleSheet("QCheckBox::indicator{width :40px;height : 40px;}")
        self.CheckStent.setChecked(False)
        self.CheckStent.setObjectName("CheckStent")
        self.NextFrameBtn = QtWidgets.QPushButton(self.centralwidget)
        self.NextFrameBtn.setEnabled(False)
        self.NextFrameBtn.setGeometry(QtCore.QRect(650, 450, 41, 61))
        self.NextFrameBtn.setObjectName("NextFrameBtn")
        self.CheckAdjcentVessel = QtWidgets.QCheckBox(self.centralwidget)
        self.CheckAdjcentVessel.setEnabled(False)
        self.CheckAdjcentVessel.setGeometry(QtCore.QRect(490, 270, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.CheckAdjcentVessel.setFont(font)
        self.CheckAdjcentVessel.setStyleSheet("QCheckBox::indicator{width :40px;height : 40px;}")
        self.CheckAdjcentVessel.setObjectName("CheckAdjcentVessel")
        self.LastFrameBtn = QtWidgets.QPushButton(self.centralwidget)
        self.LastFrameBtn.setEnabled(False)
        self.LastFrameBtn.setGeometry(QtCore.QRect(520, 450, 41, 61))
        self.LastFrameBtn.setObjectName("LastFrameBtn")
        self.SaveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SaveBtn.setEnabled(False)
        self.SaveBtn.setGeometry(QtCore.QRect(570, 450, 71, 61))
        self.SaveBtn.setObjectName("SaveBtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(520, 560, 231, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.CheckStatus = QtWidgets.QLabel(self.centralwidget)
        self.CheckStatus.setGeometry(QtCore.QRect(180, 90, 121, 16))
        self.CheckStatus.setObjectName("CheckStatus")
        Mainwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 780, 26))
        self.menubar.setObjectName("menubar")
        Mainwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Mainwindow)
        self.statusbar.setObjectName("statusbar")
        Mainwindow.setStatusBar(self.statusbar)

        self.retranslateUi(Mainwindow)
        QtCore.QMetaObject.connectSlotsByName(Mainwindow)

    def retranslateUi(self, Mainwindow):
        _translate = QtCore.QCoreApplication.translate
        Mainwindow.setWindowTitle(_translate("Mainwindow", "IVUSReviewer"))
        self.OpenFileBtn.setText(_translate("Mainwindow", "open folder"))
        self.ShowFileName.setText(_translate("Mainwindow", "folder name"))
        self.CheckBifurcation.setText(_translate("Mainwindow", "Bifuracation"))
        self.CheckCalcified.setText(_translate("Mainwindow", "Calcified Plaque"))
        self.CheckStent.setText(_translate("Mainwindow", "Stent"))
        self.NextFrameBtn.setText(_translate("Mainwindow", ">"))
        self.CheckAdjcentVessel.setText(_translate("Mainwindow", "Adjacent Vessels"))
        self.LastFrameBtn.setText(_translate("Mainwindow", "<"))
        self.SaveBtn.setText(_translate("Mainwindow", "Save"))
        self.label.setText(_translate("Mainwindow", "CopyRight © 2020 HuangBiuBiu"))
        self.CheckStatus.setText(_translate("Mainwindow", "Not Checked"))
